hibernate.connection.url = jdbc:mysql://localhost:3306/student_spring
hibernate.connection.username = root
hibernate.connection.password = sathish9846
hibernate.hbm2ddl.auto = update
hibernate.show_sql = true
hibernate.format_sql = true
hibernate.highlight_sql = true

